### ISSUE TITLE
Pop In and Out

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#12]
I had a student at TRC, Victoria B, who was initially withdrawn, then came back to us (group home situation). She's on my dropped list, but in reality she's active. How will the tracker account for these cases?

**Comment by jb-1980** [comment]
You, Ken, and I all have the same student with the same issue. Unfortunately, she appears in both active and dropped because their are two enrollment records for her. But as long as you are on top of processing the students, you will never have to touch the record again for the dropped list. It is strange because you a lot of records to process at one. 

The active will move to graded out and possibly to dropped. But they will have different end dates so you can differentiate them.

**Comment by kenburbank** [comment]
I think you can close this one.  We wouldn't want to squash the record of a previous withdrawal.  Maintaining the record of both tells the whole story.

**Comment by jb-1980** [comment]
I agree with Ken. Except for when someone first opens the app, this should not be a point of confusion. Indeed, it helps to tell the story of what has been happening with the student. I am closing.
