### ISSUE TITLE
Processed- Then What?

### ISSUE THREAD

**Issue by jsmith1213** [jb-1980/studenttracker#14]
After a student is selected as "Processed" on the Dropped List, what needs to be gone for the grade to show and them to move of this list? Or do they stay on the list forever, just not in bold font?

**Comment by jb-1980** [comment]
All processed means is that you have done whatever voodoo you do to handle that. So for example, if you have an unprocessed student in the Active tab, you may need to set them up in Galileo for benchmarks and then send them a welcome email. Once you have done your thing, you check off processed. It is a student tracker, not a student processor.

So for your specific question, when you see a student appear as not processed on the Dropped list, you should probably assign them a grade in PowerTeacher and unenroll them from the course in ELMS. When that is done, you know that you have completed the process for a dropped student and can check off the processed box next to their name, give yourself a pat on the back, and think "Wow, I am really on track with my students!".

The student will stay on the list forever. Well, technically not forever, because I imagine within 100 years it will be outdated and useless technology. But for a sufficiently long time for sure.
