### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#34]
I couldn't find how to set blackout days for the school year. I clicked as well as clicked while holding control and shift and the days won't highlight. t's labeled Spring still. Can I edit that?

**Comment by wmcfarland** [comment]
I'm still having difficulty setting the calendar to see accurate progress data. Any eta @jb-1980

**Comment by mackeyae** [comment]
I'm running into the same issues.

**Comment by jb-1980** [comment]
I decided to deprecate the whole black out calendar feature. Now it just retrieves the data from ELMS. Since I have to set dates there, I figure it is simpler to get the data from there, and it should always be a more accurate reflection of what the students are seeing.

What this means for you is you don't have to worry about black out dates anymore. It is all done behind the scenes for you.

**Comment by wmcfarland** [comment]
That is a great idea! I love it!


[1468365422595_sequoia-choice-logo_tree_200r1.png]
Mrs. Wendy McFarland M.Ed
Sequoia Choice/AzDL
U.S. History/Government Instructor
480.220.4580
wmcfarland@edkey.org<mailto:wmcfarland@edkey.org>

<mailto:wmcfarland@edkey.org>Virtual Classroom Link: https://zoom.us/j/7370068629
AZDL Facebook: <https://sas.elluminate.com/m.jnlp?sid=2012688&password=M.806F6AA574513C57A16456B596B3CF> https://www.facebook.com/scazdl

Our mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

________________________________
