### ISSUE TITLE
Question:  Blue circles

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/studenttracker#44]
Hi @jb-1980,

My tracker has new blue alert circles, but all I have are checkmarks for letters already sent.  Is this for the second round requirement?  If so, could you remind me of the parameters?

**Comment by jb-1980** [comment]
This was caused by having students enrolled in ELMS but not enrolled in PowerSchool. When they were getting to the 75% criteria they were being counted from the ELMS progress report but nothing would show up in the active students because it only displays students from PowerSchool.

I have created a check to make sure they are included in the PowerSchool enrollments, so you should not see any more extraneous blue circle alerts.

In case you were curious, the offending enrollment was a kburbank@sequoiaschools.org. Better get on him to get caught up with his course. :smile:

**Comment by kenburbank** [comment]
Ah yes, and Stella Student would be another culprit.  Thanks!




Ken Burbank

Director of Math Education, Sequoia Choice

Phone:  480-254-7698

Virtual classroom link: <https://zoom.us/j/6937843649> https://zoom.us/my/mrburbank<http://www.tinyurl.com/sequoiachoicemath>

 [1468527002671_sequoia-choice-logo_tree_200r1.png]

Our Mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

AMDG


________________________________
