### ISSUE TITLE
Graded Out Category

### ISSUE THREAD

**Issue by wmcfarland** [jb-1980/studenttracker#58]
Yes, that is supposed to happen. I created "graded out" category because when I would put a grade into PowerTeacher, it would take a while before that student was processed and I did not want them hanging out in my "active" column. Usually happened when Jeanine stored grades at end of semester. Now Jeannie is always storing grades, so it just happens.

However, I don't like that I give them a grade in ELMS and they still hang out in "Active" while I wait for Jeannie to process things. You should put a ticket in for me on studenttracker in github to fix that. It will make me feel good to check it off.

Ready to fix this?????

**Comment by jb-1980** [comment]
Students with a grade other than IP in ELMS should now be removed from the active tab, with their grades showing in the ELMS grade column in the Graded tab.

For the students in the Dropped tab, it may still be necessary to fetch the archived students to populate a grade. I prefer it this way, because for a huge class (200+ archived students) it can take a pretty second to download the data from ELMS, especially on a Friday afternoon when their is a spike in users. So best to only fetch the data when you will actually use it.
